"""make plaintext fields nullable

Revision ID: 0e180ffbb2d6
Revises: 2b3c4d5e6f7g
Create Date: 2025-11-25 21:32:21.875973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e180ffbb2d6'
down_revision = '2b3c4d5e6f7g'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
