"""add_voice_notes_fields

Revision ID: cc104efe219f
Revises: 0e180ffbb2d6
Create Date: 2025-11-26 12:21:47.166214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc104efe219f'
down_revision = '0e180ffbb2d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('audio_file_path', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('audio_duration', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('encrypted_transcription', sa.Text(), nullable=True))
    # Add has_audio as nullable first
    op.add_column('notes', sa.Column('has_audio', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE notes SET has_audio = FALSE WHERE has_audio IS NULL')
    # Now make it non-nullable
    op.alter_column('notes', 'has_audio', nullable=False)
    op.create_index(op.f('ix_notes_has_audio'), 'notes', ['has_audio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_has_audio'), table_name='notes')
    op.drop_column('notes', 'has_audio')
    op.drop_column('notes', 'encrypted_transcription')
    op.drop_column('notes', 'audio_duration')
    op.drop_column('notes', 'audio_file_path')
    # ### end Alembic commands ###
